# Setup
title: Ben Zhang
tagline: lowering your blogging standards
url: https://benzyx.github.io
paginate: 1
baseurl: ""
permalink: :title/

markdown: kramdown

kramdown:
    footnote_backlink: "&#10548;"

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-target-blank

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Ben Zhang
  url: https://twitter.com/bnzyx1
  email: frenzybenzy@gmail.com

# Custom vars
version: 1.3.0
github:
  repo: https://github.com/essentialenemy/noir

# To use Utterance comments,  you can going to https://utteranc.es/ get more parameters interpretation.
utterance:
  # Note: Make sure the repo is public, otherwise your readers will not be able to view the issues/comments.
  # Make sure the [utterances app](https://github.com/apps/utterances) is installed on the repo, otherwise users will not be able to post comments.
  #  If your repo is a fork, navigate to it's settings tab and confirm the issues feature is turned on.
  repo: benzyx/benzyx.github.io # Choose the repository utterances will connect to. eg: owner/repo
  issue-term: title   # Choose the mapping between blog posts and GitHub issues. 
  theme: github-dark # Choose an Utterances theme that matches your blog. 'github-light' is default
  label:  blog-comments # Choose the label that will be assigned to issues created by Utterances.